"""Remove custom_alias

Revision ID: 5641d4341066
Revises: ac4d20959a10
Create Date: 2026-04-09 12:42:31.001124

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5641d4341066"
down_revision: Union[str, Sequence[str], None] = "ac4d20959a10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("links", "custom_alias")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "links",
        sa.Column("custom_alias", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
