"""Make code nullable

Revision ID: ac4d20959a10
Revises: 54590ddd89d6
Create Date: 2026-04-09 01:32:52.722877

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ac4d20959a10"
down_revision: Union[str, Sequence[str], None] = "54590ddd89d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "code", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "code", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
