server {
    listen 80;

    location = /health {
        access_log off;
        return 200 "healthy\n";
    }

    location = /api-1-health {
        proxy_pass http://api-1:8000/health;
        access_log off;
    }

    location = /api-2-health {
        proxy_pass http://api-2:8000/health;
        access_log off;
    }

    location / {
        proxy_pass http://api-1:8000;
    }
}